<script setup>
import {ref,computed} from 'vue';import {useRouter} from 'vue-router';import {BookOpen,ArrowRight} from '@lucide/vue';import {authenticate} from '../lib/store';
import PasswordField from '../components/PasswordField.vue';
const router=useRouter(),mode=ref('login'),name=ref(''),email=ref(''),password=ref(''),busy=ref(false),error=ref('');
const confirmation=ref(''),confirmationTouched=ref(false);
const confirmationError=computed(()=>confirmationTouched.value && password.value!==confirmation.value ? 'As senhas não coincidem.' : '');
function changeMode(next){mode.value=next;error.value='';password.value='';confirmation.value='';confirmationTouched.value=false;}
async function submit(){error.value='';if(mode.value==='register' && password.value!==confirmation.value){confirmationTouched.value=true;document.getElementById('confirm-password')?.focus();return;}busy.value=true;try{await authenticate(mode.value,{email:email.value,password:password.value,...(mode.value==='register'?{name:name.value}:{})});router.replace('/');}catch(e){error.value=e.message;}finally{busy.value=false;}}
</script>
<template><div class="auth-layout"><section class="auth-intro"><BookOpen :size="38" :stroke-width="1.3"/><h1>Menos procura.<br>Mais aventura.</h1><p>Prepare o repertório do seu personagem e tenha cada magia ao alcance de um toque.</p><div class="auth-detail"><span>01</span><p>Escolha seu personagem e as magias da sua classe.</p></div><div class="auth-detail"><span>02</span><p>Abra a descrição completa enquanto joga.</p></div><div class="auth-detail"><span>03</span><p>Acrescente suas próprias magias e compêndios.</p></div></section>
<section class="auth-form"><span class="section-caption">Bem-vindo ao seu grimório</span><h2>{{mode==='login'?'Entre na sua conta':'Crie sua conta'}}</h2><p class="muted">Seu repertório fica guardado para a próxima sessão.</p><div class="tabs"><button :class="{active:mode==='login'}" @click="changeMode('login')">Entrar</button><button :class="{active:mode==='register'}" @click="changeMode('register')">Criar conta</button></div>
<form @submit.prevent="submit"><label v-if="mode==='register'">Seu nome<input v-model="name" autocomplete="name" required maxlength="200"/></label><label>Email<input v-model="email" type="email" autocomplete="email" required maxlength="254" placeholder="voce@exemplo.com"/></label><PasswordField :key="mode" id="password" v-model="password" :autocomplete="mode==='login'?'current-password':'new-password'" :minlength="mode==='register'?8:undefined" :pattern="mode==='register'?'(?=.*\\p{Lu})(?=.*\\p{Ll})(?=.*[0-9]).{8,256}':undefined" :hint="mode==='register'?'Use pelo menos 8 caracteres, uma letra maiúscula, uma letra minúscula e um número.':undefined"/>
<PasswordField v-if="mode==='register'" id="confirm-password" v-model="confirmation" label="Confirme sua senha" toggle-label="confirmação de senha" :error="confirmationError" @blur="confirmationTouched=true"/><p v-if="error" class="alert" role="alert">{{error}}</p><button class="button primary full" :disabled="busy">{{busy?'Aguarde…':mode==='login'?'Entrar no grimório':'Criar meu grimório'}}<ArrowRight :size="18"/></button></form></section></div></template>
