<script setup>
import CircleFilter from '../components/CircleFilter.vue';
import {ref,computed,watch,onBeforeUnmount} from 'vue';import {useRoute} from 'vue-router';import {Search,Plus,ArrowLeft,ChevronLeft,ChevronRight,Library} from '@lucide/vue';import {request} from '../lib/api';import {state,activeCharacter,refreshCharacters,notify} from '../lib/store';import SpellList from '../components/SpellList.vue';import SpellPanel from '../components/SpellPanel.vue';
const route=useRoute(),name=ref(''),school=ref(''),level=ref(''),classId=ref(activeCharacter.value?.classId||''),spells=ref([]),total=ref(0),offset=ref(0),loading=ref(true),error=ref(''),selectedId=ref(Number(route.query.magia)||null),pendingIds=ref([]);const limit=40;let controller,timer,sequence=0;
const detailFlags=ref({id:null,isPrepared:false,canPrepare:false});
const selected=computed(()=>spells.value.find(s=>s.id===selectedId.value)||detailFlags.value);
async function detailLoaded(spell){const character=activeCharacter.value;const id=spell.id;detailFlags.value={id,isPrepared:false,canPrepare:!!character&&spell.classes.some(c=>c.id===character.classId)};if(!character||spells.value.some(s=>s.id===id))return;try{const r=await request(`/characters/${character.id}/prepared-spells`);if(selectedId.value===id&&state.activeId===character.id)detailFlags.value.isPrepared=r.data.some(s=>s.id===id);}catch(e){error.value=e.message;}}
watch(selectedId,()=>{detailFlags.value={id:null,isPrepared:false,canPrepare:false};});
async function load(){controller?.abort();const c=new AbortController();controller=c;const seq=++sequence;loading.value=true;error.value='';const q=new URLSearchParams({limit:String(limit),offset:String(offset.value)});if(name.value)q.set('name',name.value);if(school.value)q.set('schoolId',school.value);if(level.value!=='')q.set('level',level.value);if(classId.value)q.set('classId',classId.value);if(state.activeId)q.set('characterId',state.activeId);
 try{const response=await request(`/spells?${q}`,{signal:c.signal});if(seq===sequence){spells.value=response.data;total.value=response.meta.total;}}catch(e){if(e.name!=='AbortError'&&seq===sequence)error.value=e.message;}finally{if(seq===sequence)loading.value=false;}}
async function toggle(spell){if(pendingIds.value.includes(spell.id))return;const character=activeCharacter.value;if(!character)return;const row=spells.value.find(s=>s.id===spell.id)||(detailFlags.value.id===spell.id?detailFlags.value:null);const prepared=row?.isPrepared??false;pendingIds.value.push(spell.id);try{await request(`/characters/${character.id}/prepared-spells/${spell.id}`,{method:prepared?'DELETE':'PUT'});if(state.activeId===character.id&&row)row.isPrepared=!prepared;await refreshCharacters();notify(`${spell.name} ${prepared?'removida das preparadas':'preparada'}.`);}catch(e){error.value=e.message;}finally{pendingIds.value=pendingIds.value.filter(id=>id!==spell.id);}}
watch([name,school,classId,level,offset,()=>state.activeId],(values,previous)=>{
 const characterChanged=values[5]!==previous[5];
 if(characterChanged){selectedId.value=null;classId.value=activeCharacter.value?.classId||'';}
 const filtersChanged=characterChanged||values.slice(0,4).some((value,index)=>value!==previous[index]);
 clearTimeout(timer);controller?.abort();sequence++;
 if(filtersChanged&&offset.value!==0){offset.value=0;return;}
 timer=setTimeout(load,filtersChanged&&!characterChanged?250:0);
});
load();onBeforeUnmount(()=>{clearTimeout(timer);sequence++;controller?.abort();});
</script>
<template><RouterLink to="/" class="back-link"><ArrowLeft :size="15"/>Voltar às preparadas</RouterLink><div class="page-heading"><div><p class="breadcrumb">Catálogo de magias</p><h1>Prepare sua próxima aventura.</h1><p class="page-description">{{activeCharacter?`Escolha as magias para ${activeCharacter.name}. Sua seleção é salva a cada escolha.`:'Explore o livro. Crie um personagem para começar a preparar magias.'}}</p></div><RouterLink to="/magias/nova" class="button"><Plus :size="17"/>Adicionar magia</RouterLink></div><div v-if="!activeCharacter" class="info-banner"><Library :size="20"/><span>Você está consultando o catálogo.</span><RouterLink to="/personagens" class="text-button">Criar personagem</RouterLink></div>
<div class="filters"><label class="search-field"><span class="sr-only">Nome da magia</span><Search :size="18"/><input v-model="name" type="search" placeholder="Buscar pelo nome da magia…"/></label><label><span>Escola</span><select aria-label="Escola" v-model="school"><option value="">Todas as escolas</option><option v-for="s in state.schools" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label><span>Classe</span><select aria-label="Classe" v-model="classId"><option value="">Todas as classes</option><option v-for="c in state.classes" :key="c.id" :value="c.id">{{c.name}}{{c.sourceKind!=='book'?' · '+c.source:''}}</option></select></label><CircleFilter v-model="level"/></div><div class="results-caption"><span>{{total}} {{total===1?'magia encontrada':'magias encontradas'}}</span><button class="text-button" v-if="name||school||classId||level!==''" @click="name='';school='';classId='';level=''">Limpar filtros</button></div><p v-if="error" class="alert" role="alert">{{error}} <button class="text-button" @click="load">Tentar novamente</button></p><div v-if="loading" class="skeleton-stack" aria-label="Carregando catálogo"><div v-for="n in 8" :key="n" class="skeleton row"></div></div><SpellList v-else-if="spells.length&&!error" :spells="spells" :selected-id="selectedId" :pending-ids="pendingIds" preparing @select="selectedId=$event" @toggle="toggle"/><div v-else-if="!error" class="empty-state"><Search :size="35"/><h2>Nenhuma magia encontrada.</h2><p>Tente outro nome ou amplie os filtros de escola, classe e círculo.</p><button class="button" @click="name='';school='';classId='';level=''">Limpar filtros</button></div><div v-if="total>limit&&!error" class="pagination"><span>{{offset+1}}–{{Math.min(offset+limit,total)}} de {{total}}</span><div><button class="button" :disabled="offset===0||loading" aria-label="Página anterior" @click="offset=Math.max(0,offset-limit)"><ChevronLeft :size="17"/>Anterior</button><button class="button" :disabled="offset+limit>=total||loading" aria-label="Próxima página" @click="offset+=limit">Próxima<ChevronRight :size="17"/></button></div></div><p class="list-footnote">O texto do livro é preservado integralmente. Magias criadas por você recebem a marca Homebrew.</p>
<SpellPanel v-if="selectedId" :id="selectedId" :prepared="!!selected?.isPrepared" :eligible="!!selected?.canPrepare" :pending="pendingIds.includes(selectedId)" @close="selectedId=null" @toggle="toggle" @changed="load" @loaded="detailLoaded"/>
</template>
