<script setup>
import {ref} from 'vue';import {Users,Plus,Pencil,Trash2,ArrowRight,X} from '@lucide/vue';import {request} from '../lib/api';import {state,refreshCharacters,chooseCharacter,notify} from '../lib/store';
const editing=ref(false),editId=ref(null),form=ref({name:'',classId:'',level:1,clearPrepared:false}),error=ref(''),busy=ref(false),deleteId=ref(null);
function edit(c){error.value='';editId.value=c?.id||null;form.value={name:c?.name||'',classId:c?.classId||state.classes[0]?.id||'',level:c?.level||1,clearPrepared:false};editing.value=true;deleteId.value=null;}
async function save(){busy.value=true;error.value='';try{const response=await request(editId.value?`/characters/${editId.value}`:'/characters',{method:editId.value?'PATCH':'POST',body:{name:form.value.name,classId:Number(form.value.classId),level:Number(form.value.level),...(editId.value?{clearPrepared:form.value.clearPrepared}:{})}});await refreshCharacters();chooseCharacter(response.data.id);editing.value=false;notify(editId.value?'Personagem atualizado.':'Personagem criado. Agora você pode preparar suas magias.');}catch(e){error.value=e.message;}finally{busy.value=false;}}
async function remove(id){busy.value=true;error.value='';try{await request(`/characters/${id}`,{method:'DELETE'});await refreshCharacters();deleteId.value=null;notify('Personagem excluído.');}catch(e){error.value=e.message;}finally{busy.value=false;}}
</script>
<template><div class="page-heading"><div><p class="breadcrumb">Sua mesa de jogo</p><h1>Personagens</h1><p class="page-description">Um repertório independente para cada aventura.</p></div><button class="button primary" @click="edit(null)"><Plus :size="17"/>Novo personagem</button></div>
<section v-if="editing" class="form-section"><div class="section-heading"><h2>{{editId?'Editar personagem':'Novo personagem'}}</h2><button class="icon-button" aria-label="Cancelar edição" @click="editing=false"><X :size="18"/></button></div><form @submit.prevent="save"><div class="form-grid"><label class="span-two">Nome<input v-model="form.name" required maxlength="200" placeholder="Como seu personagem se chama?"/></label><label>Classe<select aria-label="Classe" v-model="form.classId" required><option v-for="c in state.classes" :key="c.id" :value="c.id">{{c.name}} · {{c.source}}</option></select></label><label>Nível<input v-model="form.level" type="number" min="1" max="20" required/></label></div><label v-if="editId" class="checkbox-label"><input v-model="form.clearPrepared" type="checkbox"/>Ao trocar a classe, limpar a lista de magias preparadas.</label><p v-if="error" class="alert" role="alert">{{error}}</p><div class="form-actions"><button class="button primary" :disabled="busy">{{busy?'Salvando…':'Salvar personagem'}}</button><button type="button" class="button" @click="editing=false">Cancelar</button></div></form></section>
<div v-if="!state.characters.length&&!editing" class="empty-state"><Users :size="42" :stroke-width="1.3"/><h2>Quem vai viver esta aventura?</h2><p>Crie um personagem para selecionar magias da sua classe e guardá-las na sua conta.</p><button class="button primary" @click="edit(null)">Criar meu primeiro personagem<ArrowRight :size="17"/></button></div>
<div class="characters-list"><article v-for="c in state.characters" :key="c.id" class="character-item"><div class="character-avatar">{{c.name.slice(0,1).toUpperCase()}}</div><div class="character-description"><h2>{{c.name}}<span v-if="state.activeId===c.id" class="tag active-tag">Em jogo</span></h2><p>{{c.class}} · Nível {{c.level}} <span class="dot">·</span> {{c.preparedCount}} magias preparadas</p></div><div class="character-actions"><RouterLink class="button" to="/" @click="chooseCharacter(c.id)">Abrir grimório<ArrowRight :size="16"/></RouterLink><button class="icon-button" :aria-label="`Editar ${c.name}`" @click="edit(c)"><Pencil :size="17"/></button><button class="icon-button" :aria-label="`Excluir ${c.name}`" @click="deleteId=c.id"><Trash2 :size="17"/></button></div><div v-if="deleteId===c.id" class="delete-confirm"><p>Excluir {{c.name}} e sua lista de magias preparadas? Essa ação não pode ser desfeita.</p><button class="button danger" :disabled="busy" @click="remove(c.id)">Confirmar exclusão</button><button class="button" @click="deleteId=null">Cancelar</button><p v-if="error" role="alert">{{error}}</p></div></article></div>
</template>
