<script setup>
import {ref,computed,watch,onBeforeUnmount} from 'vue';import {Search,Plus,ArrowRight,ScrollText} from '@lucide/vue';import {request} from '../lib/api';import {state,activeCharacter,notify,refreshCharacters} from '../lib/store';import {filterPrepared,groupSpells,levelLabel} from '../lib/spells';import SpellList from '../components/SpellList.vue';import SpellPanel from '../components/SpellPanel.vue';
const spells=ref([]),loading=ref(false),error=ref(''),name=ref(''),school=ref(''),selectedId=ref(null),pendingIds=ref([]);let epoch=0;
const groups=computed(()=>groupSpells(filterPrepared(spells.value,name.value,school.value)));
async function load(){const current=++epoch;selectedId.value=null;error.value='';spells.value=[];if(!activeCharacter.value)return;loading.value=true;try{const result=await request(`/characters/${activeCharacter.value.id}/prepared-spells`);if(current===epoch)spells.value=result.data;}catch(e){if(current===epoch)error.value=e.message;}finally{if(current===epoch)loading.value=false;}}
async function remove(spell){if(pendingIds.value.includes(spell.id))return;const c=activeCharacter.value;if(!c)return;pendingIds.value.push(spell.id);try{await request(`/characters/${c.id}/prepared-spells/${spell.id}`,{method:'DELETE'});if(activeCharacter.value?.id===c.id){spells.value=spells.value.filter(s=>s.id!==spell.id);selectedId.value=null;}await refreshCharacters();notify(`${spell.name} removida das preparadas.`);}catch(e){error.value=e.message;}finally{pendingIds.value=pendingIds.value.filter(id=>id!==spell.id);}}
watch(()=>state.activeId,load,{immediate:true});onBeforeUnmount(()=>epoch++);
</script>
<template><div class="page-heading"><div><p class="breadcrumb">Seu repertório</p><h1>Magias preparadas</h1><p class="page-description">{{activeCharacter?`As magias de ${activeCharacter.name}, prontas para a próxima aventura.`:'Crie seu primeiro personagem para começar a preparar magias.'}}</p></div><RouterLink v-if="activeCharacter" class="button primary" to="/preparar"><Plus :size="18"/>Preparar magias</RouterLink></div>
<div v-if="!activeCharacter" class="empty-state"><ScrollText :size="42" :stroke-width="1.3"/><h2>Um novo grimório começa aqui.</h2><p>Dê um nome ao seu personagem, escolha sua classe e monte sua lista de magias.</p><RouterLink to="/personagens" class="button primary">Criar personagem<ArrowRight :size="17"/></RouterLink></div>
<template v-else><div class="repertoire-summary"><div><span class="summary-count">{{spells.length}}</span><span>magias preparadas</span></div><span>{{activeCharacter.class}} <span class="dot">·</span> Nível {{activeCharacter.level}}</span></div><div class="filters compact"><label class="search-field"><span class="sr-only">Buscar nas preparadas</span><Search :size="18"/><input v-model="name" placeholder="Buscar nas suas magias…" type="search"/></label><label><span class="sr-only">Escola</span><select v-model="school"><option value="">Todas as escolas</option><option v-for="s in state.schools" :key="s.id" :value="s.id">{{s.name}}</option></select></label></div><p v-if="error" class="alert" role="alert">{{error}} <button class="text-button" @click="load">Tentar novamente</button></p><div v-if="loading" class="skeleton-stack" aria-label="Carregando preparadas"><div v-for="n in 5" :key="n" class="skeleton row"></div></div><div v-else-if="!spells.length&&!error" class="empty-state"><ScrollText :size="38" :stroke-width="1.3"/><h2>Qual será sua primeira magia?</h2><p>Explore a lista de {{activeCharacter.class}} e escolha as magias que quer ter à mão.</p><RouterLink class="button primary" to="/preparar">Escolher magias<ArrowRight :size="17"/></RouterLink></div><p v-else-if="!groups.length&&!error" class="empty-search">Nenhuma magia corresponde aos filtros. <button class="text-button" @click="name='';school=''">Limpar filtros</button></p><section v-for="g in groups" :key="g.level" class="spell-group"><div class="group-heading"><h2>{{g.level===0?'Truques':levelLabel(g.level)}}</h2><span>{{g.spells.length}} {{g.spells.length===1?'magia':'magias'}}</span></div><SpellList :spells="g.spells" :selected-id="selectedId" :pending-ids="pendingIds" @select="selectedId=$event" @toggle="remove"/></section><p v-if="spells.length" class="list-footnote">Selecione o nome de uma magia para consultar a descrição completa.</p></template>
<SpellPanel v-if="selectedId" :id="selectedId" :prepared="true" :eligible="true" :pending="pendingIds.includes(selectedId)" @close="selectedId=null" @toggle="remove"/>
</template>
