<script setup>
import {ref,onMounted} from 'vue';import {useRoute,useRouter,onBeforeRouteLeave} from 'vue-router';import {ArrowLeft,Save} from '@lucide/vue';import {request} from '../lib/api';import {state,refreshReference,notify} from '../lib/store';
const route=useRoute(),router=useRouter(),editId=Number(route.params.id)||null;
const form=ref({name:'',level:0,schoolId:'',components:'',castingTime:'',range:'',duration:'',description:'',imagePath:'',classIds:[]}),busy=ref(false),loading=ref(!!editId),error=ref(''),initial=ref(''),saved=ref(false);
onMounted(async()=>{try{if(editId){const spell=(await request(`/spells/${editId}`)).data;if(spell.ownerUserId!==state.user.id||spell.sourceKind!=='homebrew')throw new Error('Só é possível editar suas próprias magias homebrew.');for(const k of Object.keys(form.value))if(k!=='classIds')form.value[k]=spell[k]??'';}else form.value.schoolId=state.schools[0]?.id||'';initial.value=JSON.stringify(form.value);}catch(e){error.value=e.message;}finally{loading.value=false;}});
onBeforeRouteLeave(()=>{if(!saved.value&&initial.value&&JSON.stringify(form.value)!==initial.value)return window.confirm('Sair sem salvar esta magia?');});
async function save(){busy.value=true;error.value='';try{const body={...form.value,level:Number(form.value.level),schoolId:Number(form.value.schoolId),imagePath:form.value.imagePath||null};if(editId)delete body.classIds;const response=await request(editId?`/spells/${editId}`:'/spells',{method:editId?'PATCH':'POST',body});saved.value=true;await refreshReference();notify(editId?'Magia homebrew atualizada.':'Magia homebrew adicionada ao seu grimório.');router.push({path:'/preparar',query:{magia:response.data.id}});}catch(e){error.value=e.message;}finally{busy.value=false;}}
</script>
<template><RouterLink class="back-link" to="/preparar"><ArrowLeft :size="15"/>Voltar ao catálogo</RouterLink><div class="page-heading"><div><p class="breadcrumb">Seu conteúdo</p><h1>{{editId?'Editar magia homebrew':'Uma nova magia para o grimório.'}}</h1><p class="page-description">{{editId?'Atualize o conteúdo da sua magia.':'Sua criação fica salva como homebrew, disponível na sua conta.'}}</p></div><span class="tag">Homebrew</span></div><div v-if="loading" class="skeleton-stack"><div v-for="n in 5" :key="n" class="skeleton row"></div></div><form v-else class="editor-form" @submit.prevent="save"><section class="form-section"><h2>Identidade da magia</h2><div class="form-grid"><label class="span-two">Nome<input v-model="form.name" required maxlength="200" placeholder="Nome da magia"/></label><label>Círculo<select aria-label="Círculo" v-model="form.level"><option :value="0">Truque (0)</option><option v-for="n in 9" :key="n" :value="n">{{n}}º círculo</option></select></label><label>Escola<select aria-label="Escola" v-model="form.schoolId" required><option value="" disabled>Selecione a escola</option><option v-for="s in state.schools" :key="s.id" :value="s.id">{{s.name}}</option></select></label></div></section><section class="form-section"><h2>Conjuração</h2><div class="form-grid"><label>Tempo de conjuração<input v-model="form.castingTime" required maxlength="8000" placeholder="Ex.: Ação"/></label><label>Alcance<input v-model="form.range" required maxlength="8000" placeholder="Ex.: 18 metros"/></label><label>Duração<input v-model="form.duration" required maxlength="8000" placeholder="Ex.: Concentração, até 1 minuto"/></label><label>Componentes<input v-model="form.components" required maxlength="8000" placeholder="Ex.: V, S, M (uma pena)"/></label></div></section><section class="form-section"><h2>Descrição completa</h2><label><span class="sr-only">Descrição da magia</span><textarea v-model="form.description" rows="11" required maxlength="120000" placeholder="Descreva os efeitos, condições e aprimoramentos da magia…"></textarea></label><p class="hint">O texto é salvo como você escrever, com pontuação e quebras de linha.</p><label>Imagem <span class="optional">(opcional)</span><input v-model="form.imagePath" maxlength="2000" placeholder="https://…"/></label></section><section v-if="!editId" class="form-section"><h2>Classes que podem escolher esta magia</h2><p class="muted">Você pode selecionar várias classes ou fazer os vínculos depois.</p><div class="class-options"><label v-for="c in state.classes" :key="c.id" class="checkbox-label"><input v-model="form.classIds" type="checkbox" :value="c.id"/><span>{{c.name}}<small>{{c.source}}</small></span></label></div></section><p v-if="error" class="alert" role="alert">{{error}}</p><div class="form-actions"><button class="button primary" :disabled="busy"><Save :size="17"/>{{busy?'Salvando…':'Salvar magia homebrew'}}</button><RouterLink class="button" to="/preparar">Cancelar</RouterLink></div></form>
</template>
