<script setup>
import {ref,onMounted,watch,onBeforeUnmount} from 'vue';import {X,Check,Plus,Pencil,BookOpen} from '@lucide/vue';import {useRouter} from 'vue-router';import {request} from '../lib/api';import {state,activeCharacter,notify} from '../lib/store';import {levelLabel} from '../lib/spells';
const props=defineProps({id:Number,prepared:Boolean,eligible:Boolean,pending:Boolean});const emit=defineEmits(['close','toggle','changed','loaded']);const router=useRouter();
const dialog=ref(),spell=ref(null),loading=ref(true),error=ref(''),classId=ref(''),linking=ref(false),linkError=ref('');let controller;
async function load(){controller?.abort();controller=new AbortController();const current=controller;loading.value=true;error.value='';try{const result=await request(`/spells/${props.id}`,{signal:current.signal});if(!current.signal.aborted){spell.value=result.data;emit('loaded',result.data);}}catch(e){if(e.name!=='AbortError')error.value=e.message;}finally{if(!current.signal.aborted)loading.value=false;}}
async function link(){linking.value=true;linkError.value='';try{await request(`/classes/${classId.value}/spells`,{method:'POST',body:{spellId:props.id}});notify('Magia adicionada à lista da classe como vínculo homebrew.');classId.value='';await load();emit('changed');}catch(e){linkError.value=e.message;}finally{linking.value=false;}}
function edit(){emit('close');router.push(`/magias/${props.id}/editar`);}
onMounted(()=>{dialog.value.showModal();load();});watch(()=>props.id,load);onBeforeUnmount(()=>controller?.abort());
</script>
<template><dialog ref="dialog" class="spell-dialog" aria-labelledby="spell-title" @close="emit('close')"><div class="panel-header"><span><BookOpen :size="17"/>Detalhes da magia</span><button class="icon-button" autofocus aria-label="Fechar detalhes" @click="dialog.close()"><X :size="20"/></button></div>
<div v-if="loading" class="panel-body skeleton-stack" aria-label="Carregando magia"><div class="skeleton title"></div><div v-for="n in 6" :key="n" class="skeleton"></div></div><div v-else-if="error" class="panel-body"><p class="alert" role="alert">{{error}}</p><button class="button" @click="load">Tentar novamente</button></div>
<article v-else-if="spell" class="panel-body"><div class="spell-eyebrow"><span class="level-badge">{{levelLabel(spell.level)}}</span><span>{{spell.school}}</span><span v-if="spell.sourceKind==='homebrew'" class="tag">Homebrew</span></div><h2 id="spell-title" class="spell-title">{{spell.name}}</h2><p class="muted source-line">{{spell.source}}<template v-if="spell.sourcePage"> · página {{spell.sourcePage}} do PDF</template></p><div class="spell-actions"><button v-if="activeCharacter" class="button" :class="prepared?'secondary':'primary'" :disabled="pending||(!prepared&&!eligible)" @click="emit('toggle',spell)"><Check v-if="prepared" :size="17"/><Plus v-else :size="17"/>{{pending?'Salvando…':prepared?'Remover das preparadas':'Preparar magia'}}</button><RouterLink v-else to="/personagens" class="button primary" @click="emit('close')">Criar personagem</RouterLink><button v-if="spell.ownerUserId===state.user.id&&spell.sourceKind==='homebrew'" class="icon-button" title="Editar magia" aria-label="Editar magia homebrew" @click="edit"><Pencil :size="18"/></button></div><p v-if="activeCharacter&&!prepared&&!eligible" class="hint">Esta magia não pertence à lista de {{activeCharacter.class}}.</p>
<dl class="spell-facts"><div><dt>Conjuração</dt><dd>{{spell.castingTime}}</dd></div><div><dt>Alcance</dt><dd>{{spell.range}}</dd></div><div><dt>Duração</dt><dd>{{spell.duration}}</dd></div><div class="span-two"><dt>Componentes</dt><dd>{{spell.components}}</dd></div></dl>
<div v-if="spell.imagePath" class="spell-image"><img :src="spell.imagePath" :alt="spell.name" referrerpolicy="no-referrer" @error="$event.target.parentElement.hidden=true"/></div><h3 class="description-heading">Descrição</h3><div class="spell-description">{{spell.description}}</div><section class="spell-class-section"><h3>Classes</h3><div class="tags"><span v-for="cl in spell.classes" :key="cl.id" class="tag">{{cl.name}}</span><span v-if="!spell.classes.length" class="muted">Nenhuma classe vinculada.</span></div><details><summary>Adicionar à lista de outra classe</summary><form class="link-form" @submit.prevent="link"><label>Classe<select aria-label="Classe" v-model="classId" required><option value="" disabled>Selecione uma classe</option><option v-for="cl in state.classes.filter(c=>!spell.classes.some(s=>s.id===c.id))" :key="cl.id" :value="cl.id">{{cl.name}} · {{cl.source}}</option></select></label><p class="hint">O vínculo será homebrew e ficará na sua conta. O texto original permanece preservado.</p><p v-if="linkError" class="alert" role="alert">{{linkError}}</p><button class="button" :disabled="linking||!classId">{{linking?'Adicionando…':'Adicionar à classe'}}</button></form></details></section></article></dialog></template>
